#RUN THIS PLAYBOOK SO THAT NODE EXPORTER IS INSTALLEDIN TARGET SERVERS

- name: Install Node Exporter
  hosts: node_exporters
  become: yes

  tasks:
    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /sbin/nologin

    - name: Download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Install binary
      copy:
        src: /tmp/node_exporter-1.7.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
        mode: 0755
        remote_src: yes

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
# Run:
# ansible-playbook -i inventory.ini node-exporter.yml
# Verify:
# curl http://10.0.0.21:9100/metrics
# curl http://10.0.0.22:9100/metrics
